#include "biblebook.h"

const QHash<int,BibleBook> bibleBooks_ {
	{1, BibleBook{1, "Gen", "Genesis", QStringList{"gn","gen","1m","im","1moj","imoj","1mojzisova","1mojz","imojz","imojzisova"}}},
	{2, BibleBook{2, "Ex", "Exodus", QStringList{"ex","exo","2m","iim","2moj","iimoj","exod","2mojzisova","2mojz","iimojzisova","iimojz"}}},
	{3, BibleBook{3, "Lev", "Leviticus", QStringList{"lv","lev","3m","iiim","3moj","iiimoj","3mojzisova","3mojz","iiimojzisova","iiimojz"}}},
	{4, BibleBook{4, "Num", "Numeri", QStringList{"nu","num","4m","ivm","4moj","ivmoj","numer","4mojzisova","4mojz","ivmojzisova","ivmojz"}}},
	{5, BibleBook{5, "Dtn", "Deuteronomium", QStringList{"dt","dtn","deut","5m","vm","5moj","vmoj","deuter","deuteron","5mojzisova","5mojz","vmojzisova","vmojz"}}},
	{6, BibleBook{6, "Joz", "Jozue", QStringList{"jozue","joz","jz"}}},
	{7, BibleBook{7, "Sd", "Soudců", QStringList{"sd","sdc","soud","soudc","soudcu"}}},
	{8, BibleBook{8, "Rt", "Rút", QStringList{"rút","rt","rut"}}},
	{9, BibleBook{9, "1Sam", "1. Samuelova", QStringList{"1s","1s","is","1sam","isam","1samuelova","isamuelova","1sm","ism","1samuel","isamuel"}}},
	{10, BibleBook{10, "2Sam", "2. Samuelova", QStringList{"2s","iis","2sam","iisam","iisamuelova","2samuelova","2sm","iism","2samuel","iisamuel"}}},
	{11, BibleBook{11, "1Kr", "1. Královská", QStringList{"1kr","ikr","1kral","ikral","ikral","1kralovska","ikralovska"}}},
	{12, BibleBook{12, "2Kr", "2. Královská", QStringList{"2kr","iikr","2kral","iikral","iikral","2kralovska","iikralovska"}}},
	{13, BibleBook{13, "1Pa", "1. Paralipomenon", QStringList{"1pa","ipa","1par","ipar","1paralipomenon","iparalipomenon","1paral","iparal","1kron"}}},
	{14, BibleBook{14, "2Pa", "2. Paralipomenon", QStringList{"2pa","iipa","2par","iipar","2paralipomenon","iiparalipomenon","2paral","iiparal","2kron"}}},
	{15, BibleBook{15, "Ezd", "Ezdráš", QStringList{"ezd","ezdr","ezdras"}}},
	{16, BibleBook{16, "Neh", "Nehemjáš", QStringList{"neh","ne","nehemjas","nehemias","nehemijas"}}},
	{17, BibleBook{17, "Est", "Ester", QStringList{"ester","est","es"}}},
	{18, BibleBook{18, "Job", "Jób", QStringList{"jb","job"}}},
	{19, BibleBook{19, "Ž", "Žalmy", QStringList{"z","zalm","zalmy","zl","zlm"}}},
	{20, BibleBook{20, "Př", "Přísloví", QStringList{"pr","prisl","pri","prislov","prislovi"}}},
	{21, BibleBook{21, "Kaz", "Kazatel", QStringList{"kaz","ka","kz","kazat","kazatel"}}},
	{22, BibleBook{22, "Pís", "Píseň písní", QStringList{"pispis","pis","pisen","pisenpisni","psn"}}},
	{23, BibleBook{23, "Iz", "Izajáš", QStringList{"iz","iza","izaj","izaias","izajas","izaijas"}}},
	{24, BibleBook{24, "Jer", "Jeremjáš", QStringList{"jr","jer","jerem","jeremias","jeremjas","jeremijas"}}},
	{25, BibleBook{25, "Pl", "Pláč", QStringList{"pl","plac"}}},
	{26, BibleBook{26, "Ez", "Ezechiel", QStringList{"ez","ezech","ezechiel"}}},
	{27, BibleBook{27, "Dan", "Daniel", QStringList{"daniel","dn","da","dan"}}},
	{28, BibleBook{28, "Oz", "Ozeáš", QStringList{"oz","oze","ozeas"}}},
	{29, BibleBook{29, "Jl", "Jóel", QStringList{"jl","jo","joel"}}},
	{30, BibleBook{30, "Am", "Ámos", QStringList{"am","amos"}}},
	{31, BibleBook{31, "Abd", "Abdijáš", QStringList{"abd","abdijas","abdias"}}},
	{32, BibleBook{32, "Jon", "Jonáš", QStringList{"jon","jona","jonas"}}},
	{33, BibleBook{33, "Mi", "Micheáš", QStringList{"mi","mich","miche","micheas"}}},
	{34, BibleBook{34, "Na", "Nahum", QStringList{"na","nah","nahum"}}},
	{35, BibleBook{35, "Aba", "Abakuk", QStringList{"ab","abk","abak","hab","hbk","habak","abakuk","habakuk"}}},
	{36, BibleBook{36, "Sf", "Sofonjáš", QStringList{"sf","sof","sofo","sofon","sofonjas","sofonias","sofonijas"}}},
	{37, BibleBook{37, "Ag", "Ageus", QStringList{"ag","age","ageus","hag","hageus","hg","hage"}}},
	{38, BibleBook{38, "Za", "Zacharjáš", QStringList{"za","zach","zachar","zacharjas","zacharias","zacharijas","zch"}}},
	{39, BibleBook{39, "Mal", "Malachjáš", QStringList{"mal","ma","malach","malachjas","malachias","malachijas"}}},
	{1001, BibleBook{1001, "Tób", "Tóbit", QStringList{"tob","tobit","tb"}}},
	{1002, BibleBook{1002, "Jdt", "Júdit", QStringList{"judit","jdt"}}},
	{1003, BibleBook{1003, "PDa", "Přídavky k Danielovi", QStringList{"pda"}}},
	{1004, BibleBook{1004, "PEst", "Přídavky k Ester", QStringList{"pest","pes"}}},
	{1005, BibleBook{1005, "Mdr", "Kniha moudrosti", QStringList{"mdr","moud","moudr","moudrost"}}},
	{1006, BibleBook{1006, "Sír", "Sírachovec", QStringList{"sir","eccl","ecc","sirach","sirachovec"}}},
	{1007, BibleBook{1007, "Bár", "Báruk", QStringList{"bar","baruk","baruch"}}},
	{1008, BibleBook{1008, "1Mak", "2. Makabejská", QStringList{"1mak","imak","1makab","imakab","1makabejska","imakabejska","1makabejskych","imakabejskych","1mk"}}},
	{1009, BibleBook{1009, "2Mak", "1. Makabejská", QStringList{"2mak","iimak","2makab","iimakab","2makabejska","iimakabejska","2makabejskych","iimakabejskych","2mk"}}},
	{40, BibleBook{40, "Mt", "Matouš", QStringList{"mt","mat","matous"}}},
	{41, BibleBook{41, "Mk", "Marek", QStringList{"mk","marek","mar"}}},
	{42, BibleBook{42, "Luk", "Lukáš", QStringList{"l","lk","luk","lukas"}}},
	{43, BibleBook{43, "Jan", "Jan", QStringList{"j","jan"}}},
	{44, BibleBook{44, "Sk", "Skutky apoštolů", QStringList{"sk","skut","skutk","akt"}}},
	{45, BibleBook{45, "Řím", "Římanům", QStringList{"r","rim","riman","rimanum"}}},
	{46, BibleBook{46, "1Kor", "1. Korintským", QStringList{"1kor","1k","ik","ikor","1korint","ikorint","1korintskym","ikorintskym"}}},
	{47, BibleBook{47, "2Kor", "2. Korintským", QStringList{"2kor","2k","iik","iikor","2korint","iikorint","2korintskym","iikorintskym"}}},
	{48, BibleBook{48, "Ga", "Galatským", QStringList{"ga","gal","galat","galatskym","gl"}}},
	{49, BibleBook{49, "Ef", "Efezským", QStringList{"ef","efes","efez","efezskym","efezkym","efeskym"}}},
	{50, BibleBook{50, "Fil", "Filipským", QStringList{"fp","f","filip","filipskym","flp","fil"}}},
	{51, BibleBook{51, "Kol", "Koloským", QStringList{"ko","kol","kolos","koloskym","kolosskym","kl"}}},
	{52, BibleBook{52, "1Te", "1. Tesalonickým", QStringList{"1te","ite","1t","it","1tes","ites","1tesal","itesal","1tesalon","itesalon","1tesalonickym","itesalonickym","1sol"}}},
	{53, BibleBook{53, "2Te", "2. Tesalonickým", QStringList{"2te","iite","2t","iit","2tes","iites","2tesal","iitesal","2tesalon","iitesalon","2tesalonickym","iitesalonickym","2sol"}}},
	{54, BibleBook{54, "1Tim", "1. Timoteovi", QStringList{"1tm","itm","1tim","itim","1timot","itimot","1timoteovi","itimoteovi","1timoteova","itimoteova"}}},
	{55, BibleBook{55, "2Tim", "2. Timoteovi", QStringList{"2tm","iitm","2tim","iitim","2timot","iitimot","2timoteovi","iitimoteovi","2timoteova","iitimoteova"}}},
	{56, BibleBook{56, "Tit", "Titovi", QStringList{"tt","tit","titova","titovi","tito"}}},
	{57, BibleBook{57, "Fm", "Filemonovi", QStringList{"fm","filem","filemon","filemonova","file"}}},
	{58, BibleBook{58, "Žd", "Židům", QStringList{"zd","zid","zidum","heb"}}},
	{59, BibleBook{59, "Jk", "List Jakubův", QStringList{"jk","jak","jakub","jakubova","jkb","jakubuv"}}},
	{60, BibleBook{60, "1Pe", "1. list Petrův", QStringList{"1pt","ipt","1p","ip","1pe","ipe","1petr","ipetr","1petrova","ipetrova"}}},
	{61, BibleBook{61, "2Pe", "2. list Petrův", QStringList{"2pt","iipt","2p","iip","2pe","iipe","2petr","iipetr","2petrova","iipetrova"}}},
	{62, BibleBook{62, "1Jan", "1. list Janův", QStringList{"1j","ij","1jan","ijan","1janova","ijanova"}}},
	{63, BibleBook{63, "2Jan", "2. list Janův", QStringList{"2j","iij","2jan","iijan","2janova","iijanova"}}},
	{64, BibleBook{64, "3Jan", "3. list Janův", QStringList{"3j","iiij","3jan","iiijan","3janova","iiijanova"}}},
	{65, BibleBook{65, "Jud", "List Judův", QStringList{"ju","juda","jd"}}},
	{66, BibleBook{66, "Zj", "Zjevení Janovo", QStringList{"zj","zjev","apok","zjv","zjeveni"}}}
};

const BibleBook errorBibleBook_ { -1, "XXX", "(neplatná kniha)", {} };

BibleBook getBibleBook(int numId)
{
	return bibleBooks_.value(numId, errorBibleBook_);
}

QList<BibleBook> bibleBookList()
{
	return bibleBooks_.values();
}
