; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Straw Lumen (x64)"
#define PlatformId "win_x86_64"
#define MyAppVersion "1.3.9.1"

#include "setup_base.iss"

[Setup]
ArchitecturesInstallIn64BitMode=x64
AppId={{553BF20E-A977-466A-8423-EDC765D05AF7}