; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


#define MyAppName "Straw Lumen"
#define PlatformId "win_x86"

#include "setup_base.iss"

[Setup]
AppId={{5DC86877-85D2-4008-ACAB-FABDE7E7888B}